version: '3.7'

services:
  main:
    build:
      context: .
      target: development
#    volumes:
#      - ./app/:/usr/src/app
#      - ./usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - 9229:9229
    command: npm run start
#    networks:
#      - webnet
    depends_on:
      - postgres
    links:
      - postgres:postgres
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
#      PG_DATA: /var/lib/postgresql/data
#    ports:
#      - 5432:5432
#    volumes:
#      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
#networks:
#  webnet:
#volumes:
#  pgdata: